server:
  port: 3000

security:
  basic:
    enabled: false

entitymanager:
  packagesToScan: com.TestAngular.*


#Database
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/testangular?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: root

#Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update



